### ISSUE TITLE
Unable to debug javascript file

### ISSUE THREAD

**Issue by wesleybl** [eclipse-wildwebdeveloper/wildwebdeveloper#1362]
After PR #1174, I can no longer debug js files. I installed the latest snapshot and I'm not able to debug js files with this new debug. I created a simple js file, right clicked on the file and selected `Debug As -> Node Program`. Then I get an error window with the message:

```
An internal error occurred during: "Launching New_configuration".
java.net.ConnectException: Connection refused
```

The console prints the message:

```
Debug server listening at 127.0.0.1:46831
```

The message appears in the log:

```
!ENTRY org.eclipse.core.jobs 4 2 2023-10-10 15:59:04.612
!MESSAGE An internal error occurred during: "Launching New_configuration".
!STACK 0
java.lang.RuntimeException: java.net.ConnectException: Connection refused
	at org.eclipse.lsp4e.debug.debugmodel.TransportStreams$SocketTransportStreams.<init>(TransportStreams.java:59)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.lambda$5(DSPLaunchDelegate.java:363)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugTarget.<init>(DSPDebugTarget.java:164)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.createDebugTarget(DSPLaunchDelegate.java:388)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.launch(DSPLaunchDelegate.java:370)
	at org.eclipse.wildwebdeveloper.debug.node.VSCodeJSDebugDelegate.launch(VSCodeJSDebugDelegate.java:201)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:805)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1038)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$1.run(DebugUIPlugin.java:1241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/java.net.Socket.connect(Socket.java:583)
	at java.base/java.net.Socket.<init>(Socket.java:507)
	at java.base/java.net.Socket.<init>(Socket.java:287)
	at org.eclipse.lsp4e.debug.debugmodel.TransportStreams$SocketTransportStreams.<init>(TransportStreams.java:55)
	... 10 more
```

**Comment by wesleybl** [comment]
@mickaelistria Can I specify the port?

**Comment by mickaelistria** [comment]
There is no option to specify the port, but if you're willing to debug Wild Web Developer, you can set a specific port in the code.

**Comment by wesleybl** [comment]
@mickaelistria I'm going to up any server here on this port and check if I can access it.

**Comment by wesleybl** [comment]
@mickaelistria I started a python server on the port and was able to access it. So it's not a network block:

```bash
$ python3 -m http.server 46831 --bind 127.0.0.1
Serving HTTP on 127.0.0.1 port 46831 (http://127.0.0.1:46831/) ...
127.0.0.1 - - [11/Oct/2023 11:50:40] "GET / HTTP/1.1" 200 -
```

**Comment by mickaelistria** [comment]
The first step of the debugger is to run `node org.eclipse.wildwebdeveloper/js-debug/src/dapDebugAdapter.js`. Can you please check this is working and then that you can connect to the given socket?
Another possibility is maybe the dns. Does `localhost` resolve to 127.0.0.1 in your case? Is IPv6 disabled? Locally, the debug adapter tells me `Debug server listening at ::1:34107` with a different IP. Maybe it matters?

**Comment by wesleybl** [comment]
@mickaelistria Is there a possibility that `TransportStreams.java` is getting the wrong host and port? The debug server appears to start correctly.

**Comment by mickaelistria** [comment]
I would say everything is possible, but I've tried many times without being able to reproduce that particular problem, CI either, and @AndrewFerr as well; so it's a bit tricky to provide more support, sorry.
Would you like to try debugging Wild Web Developer from source?

**Comment by wesleybl** [comment]
> Would you like to try debugging Wild Web Developer from source?

I'll try to debug it from the source code.

**Comment by mickaelistria** [comment]
I merged https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/pull/1367 to hopefully fix this. Let's wait for CI to complete and please retry with latest build.

**Comment by wesleybl** [comment]
@mickaelistria now I can make the debug. Thanks for the fix!

However, I am experiencing strange behavior when the debug ends. I'll open another issue about this.

**Comment by wesleybl** [comment]
@mickaelistria I had the same problem when I tried to use the `Running Node.js Application` debug:

```
!ENTRY org.eclipse.core.jobs 4 2 2023-10-17 00:14:44.319
!MESSAGE An internal error occurred during: "Launching New_configuration (1)".
!STACK 0
java.lang.RuntimeException: java.net.ConnectException: Conexão recusada
	at org.eclipse.lsp4e.debug.debugmodel.TransportStreams$SocketTransportStreams.<init>(TransportStreams.java:59)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.lambda$5(DSPLaunchDelegate.java:363)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugTarget.<init>(DSPDebugTarget.java:164)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.createDebugTarget(DSPLaunchDelegate.java:388)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.launch(DSPLaunchDelegate.java:370)
	at org.eclipse.wildwebdeveloper.debug.node.NodeAttachDebugDelegate.launch(NodeAttachDebugDelegate.java:114)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:805)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1038)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$1.run(DebugUIPlugin.java:1241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.net.ConnectException: Conexão recusada
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/java.net.Socket.connect(Socket.java:583)
	at java.base/java.net.Socket.<init>(Socket.java:507)
	at java.base/java.net.Socket.<init>(Socket.java:287)
	at org.eclipse.lsp4e.debug.debugmodel.TransportStreams$SocketTransportStreams.<init>(TransportStreams.java:55)
	... 10 more
```

**Comment by wesleybl** [comment]
`Running Node.js Application` is working now. Thanks!
