### ISSUE TITLE
[VUE] "Error while computing completion" when project name contains spaces

### ISSUE THREAD

**Issue by howlger** [eclipse-wildwebdeveloper/wildwebdeveloper#1413]
In `eclipse-jee-2023-12-RC1-win32-x86_64.zip` containing Eclipse Wild Web Developer 1.3.3.202311211923, in a project containing a space in its name, in a Vue.js file, I get from the content assist `Error while computing completion` instead of actual proposals or `no proposals`.

**Steps to reproduce**:

1. Create a general project named `Sample 1` (with a space between `Sample` and `1`) 
2. Create a file `App.vue`
3. Open the file and restart Eclipse (to make sure that no language server is reused from a project that does not contain spaces) 
4. In `App.vue` hit Ctrl+Space: content assist shows `Error while computing completion` instead of actual proposals or `no proposals`

In Eclipse Wild Web Developer 1.3.0 (Eclipse 2023-09) I can not reproduce this issue.
This might related to https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/issues/1332 

**Error**: `node.exe` is run in the directory where the space character seems to be incorrectly URI encoded as `%20`
```
eclipse.buildId=4.30.0.20231123-2204
java.version=17.0.9
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -data file:/C:/eclipse/2023-12/_ws_jee/ -product org.eclipse.epp.package.jee.product

org.eclipse.lsp4e
Error
Mon Nov 27 11:12:10 CET 2023
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\eclipse\2023-12\eclipse-jee-2023-12-RC1\.node\node-v18.18.2-win-x64\node.exe" (in directory "C:\eclipse\2023-12\_ws_jee\Sample%201"): CreateProcess error=267, Der Verzeichnisname ist ungültig

java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\eclipse\2023-12\eclipse-jee-2023-12-RC1\.node\node-v18.18.2-win-x64\node.exe" (in directory "C:\eclipse\2023-12\_ws_jee\Sample%201"): CreateProcess error=267, Der Verzeichnisname ist ungültig
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\eclipse\2023-12\eclipse-jee-2023-12-RC1\.node\node-v18.18.2-win-x64\node.exe" (in directory "C:\eclipse\2023-12\_ws_jee\Sample%201"): CreateProcess error=267, Der Verzeichnisname ist ungültig
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$0(LanguageServerWrapper.java:294)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more
Caused by: java.io.IOException: Cannot run program "C:\eclipse\2023-12\eclipse-jee-2023-12-RC1\.node\node-v18.18.2-win-x64\node.exe" (in directory "C:\eclipse\2023-12\_ws_jee\Sample%201"): CreateProcess error=267, Der Verzeichnisname ist ungültig
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at org.eclipse.lsp4e.server.ProcessStreamConnectionProvider.start(ProcessStreamConnectionProvider.java:55)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$0(LanguageServerWrapper.java:292)
	... 7 more
Caused by: java.io.IOException: CreateProcess error=267, Der Verzeichnisname ist ungültig
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 10 more
```

**Comment by JollyGood1** [comment]
I also encountered this problem.
Unfortunately I have reasons preventing me from changing the folder name.
Any chance of a fix?
