### ISSUE TITLE
Plugin not "activated" even if it appears as installed

### ISSUE THREAD

**Issue by Kiiv** [eclipse-wildwebdeveloper/wildwebdeveloper#1543]
Hi, 

since correction of [#1505](https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/issues/1505), I'm able to update the plugin again.

Unfortunately, the plugin seems not activated after update :
- there is no "Wild Web Developer" section in "preferences"
- editing a .ts file does not benefit from the different functionalities (doc, code navigation, completion) even if opened with Generic text editor
- plugin is listed in "Installed software"

```
Eclipse IDE for Java Developers (includes Incubating components)

Version: 2024-03 (4.31.0)
Build id: 20240307-1437

  Wild Web Developer HTML, CSS, JSON, Yaml, JavaScript, TypeScript, Node tools	1.3.4.202403260727	org.eclipse.wildwebdeveloper.feature.feature.group	Eclipse Wild Web Developer project
  Wild Web Developer XML tools	1.3.2.202403191205	org.eclipse.wildwebdeveloper.xml.feature.feature.group	Eclipse Wild Web Developer project
```

Don't know if I can obtain more information about what happened

**Comment by Kiiv** [comment]
Any tips to find which other plugin could cause a conflict ?

**Comment by mickaelistria** [comment]
Can you please check in your <workspace>/.metadata/.log files if the Platform emits more information about those bundles?

**Comment by Kiiv** [comment]
Ok, got this :

```
!ENTRY org.eclipse.wildwebdeveloper 4 0 2024-05-06 15:51:21.533
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.wildwebdeveloper [743]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=21))"
  Unresolved requirement: Require-Bundle: org.eclipse.wildwebdeveloper.embedder.node; bundle-version="1.0.3"
    -> Bundle-SymbolicName: org.eclipse.wildwebdeveloper.embedder.node; bundle-version="1.0.4.202403191205"
       org.eclipse.wildwebdeveloper.embedder.node [744]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=21))"

        at org.eclipse.osgi.container.Module.start(Module.java:493)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2073)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:143)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2064)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2004)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1967)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1883)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
!ENTRY org.eclipse.wildwebdeveloper.embedder.node 4 0 2024-05-06 15:51:21.535
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.wildwebdeveloper.embedder.node [744]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=21))"

        at org.eclipse.osgi.container.Module.start(Module.java:493)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2073)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:143)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2064)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2004)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1967)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1883)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
!ENTRY org.eclipse.wildwebdeveloper.xml 4 0 2024-05-06 15:51:21.537
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.wildwebdeveloper.xml [746]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=21))"

        at org.eclipse.osgi.container.Module.start(Module.java:493)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2073)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:143)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2064)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2004)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1967)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1883)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
```

It seems I need a jdk 21
 to run this ?
I'm currently using justjre embedded with eclipse and it's still on a jre 17, will try with a 21.

**Comment by Kiiv** [comment]
Unfortunately, I'll need to switch from Release to Milestone or Nigthly of the JustJ JRE for IDE packages repository :
https://download.eclipse.org/justj/epp/index.html

A lot of users will probably face this issue if they use Eclipse Packages as they are until the official build switch to JustJ JRE 21.

**Comment by nitind** [comment]
> A lot of users will probably face this issue if they use Eclipse Packages as they are until the official build switch to JustJ JRE 21.

That has been scheduled for 2024-06 for some time.
