### ISSUE TITLE
Check for updates on 1.3.3 does not update everything and leaves a broken install

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-wildwebdeveloper/wildwebdeveloper#1650]
If I unzip  https://download.eclipse.org/wildwebdeveloper/releases/1.3.3/ and check for updates (because 1.3.6 does not include a full download, see #1648) I get a partially updated Eclipse install.

To reproduce:

1. Unzip (untar, I actually did this on Linux) 1.3.3
2. Run Check for updates
3. Press back button to see following screen:

![image](https://github.com/user-attachments/assets/ed411920-8a76-4101-8f68-e41eb726a413)

4. Run the install and restart
5. Observe that Eclipse IDE 2023-09 / Eclipse Platform 4.29 is still used as the base for the install in Help -> About -> Installation Details:

![image](https://github.com/user-attachments/assets/93f6aead-d953-4fa9-a289-74ac541becf2)

7. Run check for updates again
8. A pop-up saying No remedy found is displayed:

![image](https://github.com/user-attachments/assets/a7ff370e-7551-4404-af6b-a27fd7a3b4fd)

9. The Available updates dialog opens with "Cannot complete the install because of a conflicting dependency." (full error below)

![image](https://github.com/user-attachments/assets/689647c4-a4eb-42e7-895b-862dac78660f)

Full error:

```
Cannot complete the install because of a conflicting dependency.
  Software being installed: Eclipse Help System 2.3.1800.v20240601-0610 (org.eclipse.help.feature.group 2.3.1800.v20240601-0610)
  Software currently installed: Eclipse IDE for JavaScript and Web Developers 1.3.3.202311211923 (org.eclipse.wildwebdeveloper.product 1.3.3.202311211923)
  Only one of the following can be installed at once: 
    Internet Connection Management 1.5.400.v20240413-1529 (org.eclipse.core.net 1.5.400.v20240413-1529)
    Internet Connection Management 1.5.100.v20230630-1232 (org.eclipse.core.net 1.5.100.v20230630-1232)
  Cannot satisfy dependency:
    From: Eclipse Help System 2.3.1800.v20240601-0610 (org.eclipse.help.feature.group 2.3.1800.v20240601-0610)
    To: org.eclipse.equinox.p2.iu; org.eclipse.core.net [1.5.400.v20240413-1529,1.5.400.v20240413-1529]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.29.0.v20230903-1000 (org.eclipse.platform.feature.group 4.29.0.v20230903-1000)
    To: org.eclipse.equinox.p2.iu; org.eclipse.core.net [1.5.100.v20230630-1232,1.5.100.v20230630-1232]
  Cannot satisfy dependency:
    From: Eclipse IDE for JavaScript and Web Developers 1.3.3.202311211923 (org.eclipse.wildwebdeveloper.product 1.3.3.202311211923)
    To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group [4.29.0.v20230903-1000,4.29.0.v20230903-1000]
```

---

At this point the install seems to be actually broken as the LSP features that were working before update have now stopped working, such as auto-complete:

![image](https://github.com/user-attachments/assets/7167dec9-fbbc-4d56-b899-b22d51e66bee)

In the error log there are lots errors similar to this: ([full log](https://github.com/user-attachments/files/16677976/wwd.log))

```java

!ENTRY org.eclipse.lsp4e 4 0 2024-08-20 11:21:51.351
!MESSAGE Plug-in "org.eclipse.wildwebdeveloper" was unable to instantiate class "org.eclipse.wildwebdeveloper.jsts.JSTSLanguageServer".
!STACK 1
org.eclipse.core.runtime.CoreException: Plug-in "org.eclipse.wildwebdeveloper" was unable to instantiate class "org.eclipse.wildwebdeveloper.jsts.JSTSLanguageServer".
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:212)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:206)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.lsp4e.LanguageServersRegistry$ExtensionLanguageServerDefinition.createConnectionProvider(LanguageServersRegistry.java:167)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$0(LanguageServerWrapper.java:289)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:204)
	... 12 more
Caused by: java.lang.NoSuchMethodError: 'byte[] org.apache.commons.io.IOUtils.byteArray()'
	at org.apache.commons.compress.utils.IOUtils.skip(IOUtils.java:282)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:409)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:389)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:49)
	at org.eclipse.wildwebdeveloper.embedder.node.CompressUtils.extractArchive(CompressUtils.java:71)
	at org.eclipse.wildwebdeveloper.embedder.node.CompressUtils.unarchive(CompressUtils.java:52)
	at org.eclipse.wildwebdeveloper.embedder.node.NodeJSManager.getNodeJsLocation(NodeJSManager.java:85)
	at org.eclipse.wildwebdeveloper.jsts.JSTSLanguageServer.<init>(JSTSLanguageServer.java:53)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 15 more
```

**Comment by akurtakov** [comment]
Is this still a problem?

**Comment by jonahgraham** [comment]
Yes - same behavior observed today.

**Comment by sebthom** [comment]
Can we close this issue? Since 1.3.4 no products are build anymore as of this PR https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/pull/1493 and as I understand it is about in-place upgrade of the old WWD 1.3.3 IDE
